require 'nokogiri'
require 'open-uri'
require 'pry'

# require_all './global_electricity/'
require_relative './global_electricity/version'
require_relative './global_electricity/cli'
require_relative './global_electricity/country'
require_relative './global_electricity/electricity_access'
require_relative './global_electricity/fossil_fuel'
require_relative './global_electricity/hydroelectric'
require_relative './global_electricity/nuclear_fuel'
require_relative './global_electricity/other_renewable'
require_relative './global_electricity/scraper'
